/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_ODE_ode0 0x00u /*!<@brief Open Drain Enable: Disables */
#define PCR_PE_pe0 0x00u   /*!<@brief Pull Enable: Disables */
#define PCR_PFE_pfe0 0x00u /*!<@brief Passive Filter Enable: Disables */
#define PCR_PS_ps0 0x00u   /*!<@brief Pull Select: Enables internal pulldown resistor */
#define PCR_PS_ps1 0x01u   /*!<@brief Pull Select: Enables internal pullup resistor */

/*! @name PORTD1 (number 24), Send_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON0_Send_LED_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON0_Send_LED_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_Send_LED_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_Send_LED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_Send_LED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTA21 (number 18), pressure
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_pressure_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_pressure_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_pressure_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTA20 (number 17), temp
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_temp_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_temp_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_temp_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTB5 (number 3), Electricity_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON0_Electricity_LED_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON0_Electricity_LED_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_Electricity_LED_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_Electricity_LED_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_Electricity_LED_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                      /* @} */

/*! @name PORTC7 (number 45), L_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON0_L_LED_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON0_L_LED_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_L_LED_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_L_LED_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_L_LED_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA18 (number 13), T_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON0_T_LED_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON0_T_LED_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_T_LED_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_T_LED_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_T_LED_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTA19 (number 14), P_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON0_P_LED_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON0_P_LED_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_P_LED_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_P_LED_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_P_LED_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTD2 (number 25), BLE_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON0_BLE_LED_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON0_BLE_LED_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_BLE_LED_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_BLE_LED_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_BLE_LED_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTC6 (number 44), electricity
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_electricity_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_electricity_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_electricity_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORTB4 (number 2), ON
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON0_ON_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON0_ON_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_ON_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_ON_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_ON_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinButton0(void);

/*! @name PORTC6 (number 44), electricity
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON1_SW3_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON1_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON1_SW3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON1_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON1_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinButton1(void);

/*!
 * @brief Configures pin routing to route SWO to GPIO (only one pin alternate (alt5) is available for SWO on KW45)
 *
 */
void BOARD_InitPinSWO(void);

/*! @name PORTB0 (number 46), LED1/LPSPI1_PCS0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINLED1_LED1_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINLED1_LED1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINLED1_LED1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINLED1_LED1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINLED1_LED1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLED1(void);

/*! @name PORTA21 (number 18), pressure
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINLED2_LED_R_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINLED2_LED_R_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINLED2_LED_R_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINLED2_LED_R_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINLED2_LED_R_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLED2(void);

/*! @name PORTA19 (number 14), P_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINLED3_LED_G_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINLED3_LED_G_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINLED3_LED_G_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINLED3_LED_G_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINLED3_LED_G_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLED3(void);

/*! @name PORTA20 (number 17), temp
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINLED4_LED_B_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINLED4_LED_B_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINLED4_LED_B_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINLED4_LED_B_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINLED4_LED_B_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLED4(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART0_RX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART0_TX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART1_RX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART1_TX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART0_RX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART0_TX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART1_RX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART1_TX(void);

/*! @name PORTC6 (number 44), electricity
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINBUTTON1_SW3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINBUTTON1_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINBUTTON1_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinButton1(void);

/*! @name PORTD1 (number 24), Send_LED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINBUTTON0_SW2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINBUTTON0_SW2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINBUTTON0_SW2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinButton0(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinSWO(void);

/*! @name PORTB0 (number 46), LED1/LPSPI1_PCS0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINLED1_LED1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINLED1_LED1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINLED1_LED1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLED1(void);

/*! @name PORTA21 (number 18), pressure
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINLED2_LED_R_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINLED2_LED_R_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINLED2_LED_R_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLED2(void);

/*! @name PORTA19 (number 14), P_LED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINLED3_LED_G_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINLED3_LED_G_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINLED3_LED_G_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLED3(void);

/*! @name PORTA20 (number 17), temp
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINLED4_LED_B_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINLED4_LED_B_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINLED4_LED_B_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLED4(void);

/*! @name PORTB2 (number 48), SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITEXTFLASHPINS_SCKSI_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTFLASHPINS_SCKSI_IO1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTFLASHPINS_SCKSI_IO1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORTB1 (number 47), SI_IO1/SI-IO1/SI-IO1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITEXTFLASHPINS_SI_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTFLASHPINS_SI_IO1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTFLASHPINS_SI_IO1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB3 (number 1), SO_IO1/SO-IO1/SO-IO1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITEXTFLASHPINS_SO_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTFLASHPINS_SO_IO1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTFLASHPINS_SO_IO1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB0 (number 46), LED1/LPSPI1_PCS0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEXTFLASHPINS_LPSPI1_PCS0_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEXTFLASHPINS_LPSPI1_PCS0_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITEXTFLASHPINS_LPSPI1_PCS0_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITEXTFLASHPINS_LPSPI1_PCS0_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEXTFLASHPINS_LPSPI1_PCS0_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITEXTFLASHPINS_LPSPI1_PCS0_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitExtFlashPins(void);

/*! @name PORTB0 (number 46), LED1/LPSPI1_PCS0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DEINITEXTFLASHPINS_LPSPI1_PCS0_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_DEINITEXTFLASHPINS_LPSPI1_PCS0_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_DEINITEXTFLASHPINS_LPSPI1_PCS0_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_DEINITEXTFLASHPINS_LPSPI1_PCS0_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_DEINITEXTFLASHPINS_LPSPI1_PCS0_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_DEINITEXTFLASHPINS_LPSPI1_PCS0_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                      /* @} */

/*! @name PORTB1 (number 47), SI_IO1/SI-IO1/SI-IO1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DEINITEXTFLASHPINS_SI_IO1_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_DEINITEXTFLASHPINS_SI_IO1_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_DEINITEXTFLASHPINS_SI_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_DEINITEXTFLASHPINS_SI_IO1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_DEINITEXTFLASHPINS_SI_IO1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTB2 (number 48), SCK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DEINITEXTFLASHPINS_SCKSI_IO1_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_DEINITEXTFLASHPINS_SCKSI_IO1_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_DEINITEXTFLASHPINS_SCKSI_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_DEINITEXTFLASHPINS_SCKSI_IO1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_DEINITEXTFLASHPINS_SCKSI_IO1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORTB3 (number 1), SO_IO1/SO-IO1/SO-IO1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_DEINITEXTFLASHPINS_SO_IO1_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_DEINITEXTFLASHPINS_SO_IO1_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_DEINITEXTFLASHPINS_SO_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_DEINITEXTFLASHPINS_SO_IO1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_DEINITEXTFLASHPINS_SO_IO1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_DeinitExtFlashPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART0_RTS(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART0_CTS(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART0_RTS(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART0_CTS(void);

/*!
 * @brief Configures pin routing, Disable pin 10 for leakage reduction in low power mode.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
